### ISSUE TITLE
Several little bugs in the setup

### ISSUE THREAD

**Issue by xindonglin99** [jinseokbae/pmp#1]
Hi Jinseok,

1. When I do `pip install -e .`, it shows the `python_requires=">=3.6.*"` is invalid. I changed it to `python_requires=">=3.6",` and it was successfully installed.

2. the running command for hand gym has a typo. The task should be "HandGraspGym" not "HandGrapGym". Also it's better to add a `cd isaacgymenvs` before the training command just so the user can train directly from copy/paste.

Thanks a lot for posting the code again!

Best regards,
Xindong

**Comment by jinseokbae** [comment]
Hi @xindonglin99,
thanks for the valuable comments!

I double-checked your suggestion on `setup.py` and reflected it to the main branch.

Also, I revised the typo in README as well.

If there's no more issue on this, I will close this issue.

Best regards,
Jinseok
